version: "3.8"
services:
  database:
    container_name: meeti-db
    image: postgis/postgis
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: meeti
    volumes:
      - ~/docker/db/meeti/v1.0/postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  server:
    container_name: meeti-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    links: 
      - database
    depends_on: 
      - database
    environment:
      WAIT_HOSTS: database:5432
      WAIT_BEFORE: 60
      WAIT_SLEEP_INTERVAL: 60
      WAIT_HOST_CONNECT_TIMEOUT: 30      
